name: AzureSponge
version: 1.0.0
api-version: 1.18
description: Upgraded Sponge
author: Azuremoon
main: xyz.azuremoon.AzureSponge

permissions:

    sponge.use:
      default: true

#     YET TO BE IMPLEMENTED   #
#    sponge.shield:
#      default: false

    sponge.lava:
      description: Always Sponge to remove lava in set radius
      default: true

    sponge.dry:
      description: Allows sponge to remain dry after each use
      default: op