name: AzureSponge
version: 1.0.0
api-version: 1.18
description: Upgraded Sponge
author: Azuremoon
main: xyz.azuremoon.AzureSponge

permissions:

    sponge.use:
      default: true

    sponge.lava:
      description: Always Sponge to remove lava in set radius
      default: true

    sponge.shield:
      description: Places a barrier at edge of drain radius to prevent water ingress while sponge is in place
      default: op

    sponge.dry:
      description: Allows sponge to remain dry after each use
      default: op