name: AzureSponge
version: 1.4.0
api-version: 1.18
description: Upgraded Sponge
author: Azuremoon
main: xyz.azuremoon.AzureSponge

commands:

  spongeadj:
    permission: sponge.adj
    aliases: as

permissions:

    sponge.use:
      default: true

    sponge.lava:
      description: Always Sponge to remove lava in set radius
      default: true

    sponge.shield:
      description: Places a barrier at edge of drain radius to prevent water ingress while sponge is in place
      default: true

    sponge.dry:
      description: Allows sponge to remain dry after each use
      default: true

    sponge.adj:
      description: Allows on the fly sponge Radius adjustments
      default: true

    sponge.fill:
      description: Allows player to use Saturated sponges.
      default: true

    sponge.fillAdj:
      description: Allows player to adj Saturated sponges.
      default: true